spring:
  application:
    name: MomentService
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:18375
        failure-tolerance-enabled: true
        naming-load-cache-at-start: true
        fail-fast: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:13306/threadora?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: gK3T9n%q2M@j7Z4
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      initialization-fail-timeout: 10000
      idle-timeout: 30000
      max-lifetime: 60000
      connection-timeout: 30000
      validation-timeout: 3000
      connection-test-query: SELECT 1
      pool-name: HikariCP
  jmx:
    enabled: true
  redis:
    host: 127.0.0.1
    port: 59000
    password: e65K4t8w2

server:
  tomcat:
    connection-timeout: 60000
  port: 8086

logging:
  level:
    com.threadora.moment.mapper: debug
