server:
  port: 10010

spring:
  application:
    name: GateWay
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:18375
        failure-tolerance-enabled: true
        naming-load-cache-at-start: true
        fail-fast: false
    gateway:
      httpclient:
        connect-timeout: 60000
        response-timeout: 60000
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
              - "http://127.0.0.1:5173"
              - "http://localhost:10010"
              - "http://127.0.0.1:10010"
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "PATCH"
              - "OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 36000
      routes:
        - id: AuthenticationService
          uri: lb://AuthenticationService
          predicates:
            - Path=/api/v1/user/**
          filters:
            - AddRequestHeader=X-Request-Source, InfiniteChat-GateWay
            - AddResponseHeader=X-Response-Source, InfiniteChat-GateWay

        - id: RealTimeCommunicationService
          uri: lb://RealTimeCommunicationService
          predicates:
            - Path=/api/v1/message/**

        - id: NettyService
          uri: lb:ws://NettyService
          predicates:
            - Path=/api/v1/netty

        - id: OfflineDataStoreService
          uri: lb://OfflineDataStoreService
          predicates:
            - Path=/api/v1/offline/**

        - id: MessagingService
          uri: lb://MessagingService
          predicates:
            - Path=/api/v1/chat/**

        - id: MomentService
          uri: lb://MomentService
          predicates:
            - Path=/api/v1/moment/**

        - id: ContactService
          uri: lb://ContactService
          predicates:
            - Path=/api/v1/contact/**

        - id: InfiniteChatAgent
          uri: http://127.0.0.1:8087
          predicates:
            - Path=/api/v1/ai/**
          filters:
            - RewritePath=/api/v1/ai/(?<segment>.*), /api/${segment}
            - AddRequestHeader=X-Request-Source, InfiniteChat-GateWay
